INSERT INTO media_assets (competitor_name, product_area, product_sub_area, page_url, storage_url, cdn_url, media_type, source_type, is_active, metadata)
VALUES
('SAP Analytics Cloud', 'Reporting & Analytics', 'Dashboards & Visualization', 
 'https://community.sap.com/t5/technology-blog-posts-by-sap/visualizing-data-with-sap-analytics-cloud/ba-p/14033467',
 'https://community.sap.com/t5/image/serverpage/image-id/240818i7AE98E0B31FA43F4/image-size/large?v=v2&px=999',
 'https://community.sap.com/t5/image/serverpage/image-id/240818i7AE98E0B31FA43F4/image-size/large?v=v2&px=999',
 'image', 'inline', true, '{"crawl_source": "targeted-crawl", "source_blog": "SAP Community - Visualizing Data"}'::jsonb),
('SAP Analytics Cloud', 'Reporting & Analytics', 'Dashboards & Visualization',
 'https://community.sap.com/t5/technology-blog-posts-by-sap/visualizing-data-with-sap-analytics-cloud/ba-p/14033467',
 'https://community.sap.com/t5/image/serverpage/image-id/240832iAA8597AB8FDBE78D/image-size/medium?v=v2&px=400',
 'https://community.sap.com/t5/image/serverpage/image-id/240832iAA8597AB8FDBE78D/image-size/medium?v=v2&px=400',
 'image', 'inline', true, '{"crawl_source": "targeted-crawl", "source_blog": "SAP Community - Time Analysis Charts"}'::jsonb),
('SAP Analytics Cloud', 'Reporting & Analytics', 'Dashboards & Visualization',
 'https://community.sap.com/t5/technology-blog-posts-by-sap/introducing-the-sap-analytics-cloud-dashboard-hi-fi-ui-kit/ba-p/14277840',
 'https://community.sap.com/t5/image/serverpage/image-id/345287iDBE7A4695386AB1E/image-size/large?v=v2&px=999',
 'https://community.sap.com/t5/image/serverpage/image-id/345287iDBE7A4695386AB1E/image-size/large?v=v2&px=999',
 'image', 'inline', true, '{"crawl_source": "targeted-crawl", "source_blog": "SAP Community - Dashboard Templates"}'::jsonb),
('SAP Analytics Cloud', 'Reporting & Analytics', 'Dashboards & Visualization',
 'https://community.sap.com/t5/technology-blog-posts-by-sap/introducing-the-sap-analytics-cloud-dashboard-hi-fi-ui-kit/ba-p/14277840',
 'https://community.sap.com/t5/image/serverpage/image-id/345288iBDE4EAB7BB6860DB/image-size/large?v=v2&px=999',
 'https://community.sap.com/t5/image/serverpage/image-id/345288iBDE4EAB7BB6860DB/image-size/large?v=v2&px=999',
 'image', 'inline', true, '{"crawl_source": "targeted-crawl", "source_blog": "SAP Community - Dashboard Components"}'::jsonb),
('SAP Analytics Cloud', 'Modeling & Architecture', 'Standard Sheets',
 'https://solatatech.com/article/create-planning-model-from-scratch-in-sap-analytics-cloud',
 'https://i0.wp.com/blogs.sap.com/legacyfs/online/storage/blog_attachments/2017/12/1-43.png',
 'https://i0.wp.com/blogs.sap.com/legacyfs/online/storage/blog_attachments/2017/12/1-43.png',
 'image', 'inline', true, '{"crawl_source": "targeted-crawl", "source_blog": "SAP Blog - Planning Model Creation"}'::jsonb),
('SAP Analytics Cloud', 'Modeling & Architecture', 'Standard Sheets',
 'https://solatatech.com/article/create-planning-model-from-scratch-in-sap-analytics-cloud',
 'https://i0.wp.com/blogs.sap.com/legacyfs/online/storage/blog_attachments/2017/12/3-36.png',
 'https://i0.wp.com/blogs.sap.com/legacyfs/online/storage/blog_attachments/2017/12/3-36.png',
 'image', 'inline', true, '{"crawl_source": "targeted-crawl", "source_blog": "SAP Blog - Enable Planning"}'::jsonb),
('SAP Analytics Cloud', 'Modeling & Architecture', 'Dimensions & Attributes',
 'https://solatatech.com/article/create-planning-model-from-scratch-in-sap-analytics-cloud',
 'https://i0.wp.com/blogs.sap.com/legacyfs/online/storage/blog_attachments/2017/12/7-23.png',
 'https://i0.wp.com/blogs.sap.com/legacyfs/online/storage/blog_attachments/2017/12/7-23.png',
 'image', 'inline', true, '{"crawl_source": "targeted-crawl", "source_blog": "SAP Blog - Time Dimension"}'::jsonb),
('SAP Analytics Cloud', 'Modeling & Architecture', 'Dimensions & Attributes',
 'https://solatatech.com/article/create-planning-model-from-scratch-in-sap-analytics-cloud',
 'https://i0.wp.com/blogs.sap.com/legacyfs/online/storage/blog_attachments/2017/12/9-24.png',
 'https://i0.wp.com/blogs.sap.com/legacyfs/online/storage/blog_attachments/2017/12/9-24.png',
 'image', 'inline', true, '{"crawl_source": "targeted-crawl", "source_blog": "SAP Blog - Account Dimension"}'::jsonb),
('SAP Analytics Cloud', 'Modeling & Architecture', 'Dimensions & Attributes',
 'https://solatatech.com/article/create-planning-model-from-scratch-in-sap-analytics-cloud',
 'https://i0.wp.com/blogs.sap.com/legacyfs/online/storage/blog_attachments/2017/12/4-29.png',
 'https://i0.wp.com/blogs.sap.com/legacyfs/online/storage/blog_attachments/2017/12/4-29.png',
 'image', 'inline', true, '{"crawl_source": "targeted-crawl", "source_blog": "SAP Blog - Model Preferences"}'::jsonb),
('SAP Analytics Cloud', 'Intelligent Planning', 'Predictive Forecaster',
 'https://insightcubes.com/blog/smart-features/time-series-forecasting-in-sap-analytics-cloud-smart-predict/',
 'https://insightcubes.com/wp-content/uploads/2025/10/InsightCubes_Time_Series_SAC-1024x335.jpg',
 'https://insightcubes.com/wp-content/uploads/2025/10/InsightCubes_Time_Series_SAC-1024x335.jpg',
 'image', 'inline', true, '{"crawl_source": "targeted-crawl", "source_blog": "InsightCubes - Time Series Forecasting"}'::jsonb),
('SAP Analytics Cloud', 'Integration', 'Data Integration',
 'https://solatatech.com/article/create-planning-model-from-scratch-in-sap-analytics-cloud',
 'https://i0.wp.com/blogs.sap.com/legacyfs/online/storage/blog_attachments/2017/12/6-21.png',
 'https://i0.wp.com/blogs.sap.com/legacyfs/online/storage/blog_attachments/2017/12/6-21.png',
 'image', 'inline', true, '{"crawl_source": "targeted-crawl", "source_blog": "SAP Blog - Currency Data Config"}'::jsonb),
('Anaplan', 'Intelligent Planning', 'Predictive Forecaster',
 'https://www.anaplan.com/platform/intelligence/',
 'https://www.anaplan.com/content/dam/anaplan/assets/images/graphics/platform/dashboards/anaplan-intelligence-phases-forward-looking-insights-with-predictive-ai.jpg',
 'https://www.anaplan.com/content/dam/anaplan/assets/images/graphics/platform/dashboards/anaplan-intelligence-phases-forward-looking-insights-with-predictive-ai.jpg',
 'image', 'inline', true, '{"crawl_source": "targeted-crawl", "source_blog": "Anaplan.com - Predictive AI"}'::jsonb),
('Anaplan', 'Intelligent Planning', 'Planning Agent',
 'https://www.anaplan.com/platform/intelligence/',
 'https://www.anaplan.com/content/dam/anaplan/assets/images/graphics/platform/dashboards/anaplan-intelligence-phases-accelerated-decision-making-and-model-building.jpg',
 'https://www.anaplan.com/content/dam/anaplan/assets/images/graphics/platform/dashboards/anaplan-intelligence-phases-accelerated-decision-making-and-model-building.jpg',
 'image', 'inline', true, '{"crawl_source": "targeted-crawl", "source_blog": "Anaplan.com - CoModeler"}'::jsonb),
('Anaplan', 'Intelligent Planning', 'Anomaly Detection',
 'https://www.anaplan.com/platform/intelligence/',
 'https://www.anaplan.com/content/dam/anaplan/assets/images/graphics/platform/dashboards/anaplan-intelligence-phases-turn-insights-into-action-with-autonomous-agents.jpg',
 'https://www.anaplan.com/content/dam/anaplan/assets/images/graphics/platform/dashboards/anaplan-intelligence-phases-turn-insights-into-action-with-autonomous-agents.jpg',
 'image', 'inline', true, '{"crawl_source": "targeted-crawl", "source_blog": "Anaplan.com - Anomaly Detector"}'::jsonb),
('Anaplan', 'Intelligent Planning', 'Planning Agent',
 'https://www.anaplan.com/platform/intelligence/',
 'https://www.anaplan.com/content/dam/anaplan/assets/images/graphics/platform/dashboards/anaplan-intelligence-phases-create-and-control-custom-ai-agents.jpg',
 'https://www.anaplan.com/content/dam/anaplan/assets/images/graphics/platform/dashboards/anaplan-intelligence-phases-create-and-control-custom-ai-agents.jpg',
 'image', 'inline', true, '{"crawl_source": "targeted-crawl", "source_blog": "Anaplan.com - Agent Studio"}'::jsonb)
ON CONFLICT DO NOTHING;