
INSERT INTO media_assets (competitor_name, product_area, product_sub_area, page_url, storage_url, media_type, source_type, alt_text, metadata)
VALUES
-- Web-Based Matrix Reporting (Cube View)
('OneStream', 'Reporting & Analytics', 'Web-Based Matrix Reporting', 'https://www.mindstreamanalytics.com/blog/onestream-cube-view-right-click-dashboard-navigation.html', 'https://www.mindstreamanalytics.com/images/blog/1-cube-view-right-click-menu.webp', 'image', 'inline', 'OneStream Cube View right-click menu for dashboard navigation', '{"is_product_ui": true, "crawl_source": "manual_verified"}'),
('OneStream', 'Reporting & Analytics', 'Web-Based Matrix Reporting', 'https://www.mindstreamanalytics.com/blog/onestream-cube-view-right-click-dashboard-navigation.html', 'https://www.mindstreamanalytics.com/images/blog/3-main-dashboard-cube-view.webp', 'image', 'inline', 'OneStream main dashboard with Cube View component', '{"is_product_ui": true, "crawl_source": "manual_verified"}'),
('OneStream', 'Reporting & Analytics', 'Web-Based Matrix Reporting', 'https://www.mindstreamanalytics.com/blog/onestream-cube-view-right-click-dashboard-navigation.html', 'https://www.mindstreamanalytics.com/images/blog/7-cube-view-navigation-links.webp', 'image', 'inline', 'OneStream Cube View navigation links configuration', '{"is_product_ui": true, "crawl_source": "manual_verified"}'),
('OneStream', 'Reporting & Analytics', 'Web-Based Matrix Reporting', 'https://blogs.perficient.com/2022/10/26/onestream-a-simple-guide-to-building-reports-and-dashboards-part-1-of-3/', 'https://blogs.perficient.com/files/Completed-Cube-View-Report-300x59.png', 'image', 'inline', 'OneStream completed Cube View financial report with matrix layout', '{"is_product_ui": true, "crawl_source": "manual_verified"}'),

-- Drill-Through
('OneStream', 'Collaboration & Workflow', 'Drill-Through', 'https://www.onestream.com/blog/onestream-xf-drill-through-and-drill-all-the-way-back/', 'https://cdn.sanity.io/images/8riso4ej/production/28c3a6bec60d69e0507e40fec75c32c0f1af4caa-451x244.png?w=4000&q=93&fit=max&auto=format', 'image', 'inline', 'OneStream XF drill-through interface showing one-click data navigation', '{"is_product_ui": true, "crawl_source": "manual_verified"}'),
('OneStream', 'Collaboration & Workflow', 'Drill-Through', 'https://www.onestream.com/blog/onestream-xf-drill-through-and-drill-all-the-way-back/', 'https://cdn.sanity.io/images/8riso4ej/production/7228e8e6d3cd461159e971d54dc7ca96d51dd1ca-485x262.png?w=4000&q=93&fit=max&auto=format', 'image', 'inline', 'OneStream XF drill-back to source system data view', '{"is_product_ui": true, "crawl_source": "manual_verified"}'),
('OneStream', 'Collaboration & Workflow', 'Drill-Through', 'https://www.mindstreamanalytics.com/blog/onestream-cube-view-right-click-dashboard-navigation.html', 'https://www.mindstreamanalytics.com/images/blog/8-cube-view-navigation-result.webp', 'image', 'inline', 'OneStream drill-through navigation result showing linked dashboard', '{"is_product_ui": true, "crawl_source": "manual_verified"}'),

-- Consolidation
('OneStream', 'Specialized Planning Modules', 'Consolidation', 'https://www.mindstreamanalytics.com/blog/visualizing-and-streamlining-data-and-processes-with-onestream-dashboards.html', 'https://www.mindstreamanalytics.com/images/blog/OneStream-Dashboards-sample-admin-tasks.jpg', 'image', 'inline', 'OneStream consolidation workflow dashboard with admin tasks and process management', '{"is_product_ui": true, "crawl_source": "manual_verified"}'),

-- Cell Notes & Audit Trail
('OneStream', 'Collaboration & Workflow', 'Cell Notes & Audit Trail', 'https://www.mindstreamanalytics.com/blog/onestream-cube-view-right-click-dashboard-navigation.html', 'https://www.mindstreamanalytics.com/images/blog/2-cube-view-source-setup.webp', 'image', 'inline', 'OneStream Cube View source setup showing cell-level configuration and audit properties', '{"is_product_ui": true, "crawl_source": "manual_verified"}'),
('OneStream', 'Collaboration & Workflow', 'Cell Notes & Audit Trail', 'https://www.mindstreamanalytics.com/blog/onestream-cube-view-right-click-dashboard-navigation.html', 'https://www.mindstreamanalytics.com/images/blog/4-cube-view-dashboard-component.webp', 'image', 'inline', 'OneStream dashboard component configuration with audit trail properties', '{"is_product_ui": true, "crawl_source": "manual_verified"}'),

-- Sales Planning (using dashboard visualization showing financial planning data)
('OneStream', 'Specialized Planning Modules', 'Sales Planning', 'https://www.mindstreamanalytics.com/blog/visualizing-and-streamlining-data-and-processes-with-onestream-dashboards.html', 'https://www.mindstreamanalytics.com/images/blog/OneStream-Dashboards-sample-visualizations.jpg', 'image', 'inline', 'OneStream planning dashboard with sales performance visualizations and charts', '{"is_product_ui": true, "crawl_source": "manual_verified"}'),
('OneStream', 'Specialized Planning Modules', 'Sales Planning', 'https://blogs.perficient.com/2022/10/26/onestream-a-simple-guide-to-building-reports-and-dashboards-part-1-of-3/', 'https://blogs.perficient.com/files/GolfStream-Raw-Sales-Data-300x93.png', 'image', 'inline', 'OneStream GolfStream sales data in cube view with product income breakdown', '{"is_product_ui": true, "crawl_source": "manual_verified"}');
